### ISSUE TITLE
Proxy checker

### ISSUE THREAD

**Issue by Trinitas** [michaeldegroot/socket-anti-spam#23]
Is a proxy checker on the list "to do"  ?

**Comment by michaeldegroot** [comment]
Is there a way to systematically detect proxies? I think I tried to solve this solution waaay back with some php scripting (back in 2005 or something lol) but there was never a 100% sure way of knowing if someone had a proxy, you could make blacklist's with known proxy providers and I could create a feature where it could load a text file or something full of blacklisted ip's and deny any access if a user is using one of them.

**Comment by Trinitas** [comment]
There is some "node proxy cheker" available. I have no clue how it works. But I'm sure they don't use blacklisted IP addresses

**Comment by michaeldegroot** [comment]
I cannot find a reliable way to know if a ip address is a proxy. Seems like blacklisting is the only available option.

You can use the authenticate event https://github.com/michaeldegroot/socket-anti-spam#eventonauthenticate-callback to get the ip adress on connection and disconnect the socket if it is in your blacklist ip's.
