### ISSUE TITLE
Sliding Window

### ISSUE THREAD

**Issue by p0d3r** [michaeldegroot/socket-anti-spam#24]
An advanced improvement but, anyone could want to use sliding window algorithm to determine when to ban a user.

**Comment by michaeldegroot** [comment]
Can you explain more about this issue. I'm unable to see what you exactly mean here.

**Comment by michaeldegroot** [comment]
Do you mean to detect a spike or a frequency? It's unclear for me what you ask here.. Please re-adress and I will open the ticket
