### ISSUE TITLE
Load Balancer Support

### ISSUE THREAD

**Issue by depyronick** [michaeldegroot/socket-anti-spam#25]
Gathered data should be kept on a (cache provider || database) to give ability to use the module behind load balancer.

**Comment by p0d3r** [comment]
Well I'm not sure about this, but we need to be sure if this module works with socket io adapters like Redis adapter (socket.io-redis)

**Comment by michaeldegroot** [comment]
Seems like a solid improvement, It has been thrown in to the TODO :)
