### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Blamo27** [michaeldegroot/socket-anti-spam#32]
Hello,

There is a memory in your code.
`var heartbeats ` is never cleared.

You must add :
`delete heartbeats[socket.id]`

In your function clearHeart :
`function clearHeart(socket)` 

var users too, is not cleared properly

There is not informations about what is heartbeat for

**Comment by qassa** [comment]
I guess that heartbeat and ererything connected is a kind of Token Bucket Algorithm (or leaky bucket, don't know the difference between them).

It helps to control the data flow and limit it.
Parameters are set in `defaultOptions`. At least `heartBeatCheck` looks like the next tick.

And this makes the clock to tick. But 4 default secs seems to run a bit longer than 1 sec actually does.
`setInterval(checkHeart, options.heartBeatCheck * 1000, socket);`

**Comment by michaeldegroot** [comment]
Heartbeat was made for a bug where a user would have multiple windows open and close some.. I can't find the source now and I wish I made tests for it.. but it has a proven reason why it's here.

If there is indeed a memory leak, this is concerning.. I do not have a lot of time currently but I will do some tests for this as soon as I can.. In the mean time.. please feel free to send pull requests

**Comment by michaeldegroot** [comment]
will be fixed in next version
