### ISSUE TITLE
Custom spam score for certain emits

### ISSUE THREAD

**Issue by madprops** [michaeldegroot/socket-anti-spam#34]
Hi, thank you for this great library. 

I just stumbled upon a problem. I've implemented sliced uploads, meaning instead of uploading the full file, I make an emit every 100kb. This triggered the anti spam system. 

So now I have to either increase the anti spam threshold to a much higher number, or somehow make an exception to those emits, to make them add to the spamscore less or something. 

I'm wondering if there's some way to add some sort of exceptions to certain emits.

**Comment by michaeldegroot** [comment]
Yes, do not use the `io` parameter in the antiSpam.init function so it will not auto bind to emits... and then use https://github.com/michaeldegroot/socket-anti-spam#addspamsocket to add spam scores to your defines emits

**Comment by madprops** [comment]
Cool. Only inconvenience with that is that there doesn't seem to be a way to add a specific amount of score, so i'd have to make a loop to add a score of 100 for example
