### ISSUE TITLE
Request: Promise implementation

### ISSUE THREAD

**Issue by madprops** [michaeldegroot/socket-anti-spam#36]
Hello. It would be nice if this library was promised based, since it opens many possibilities and keeps it more up to date with modern standards. This would allow the library to be used with "await" expressions for example, which I think can be beneficial for the addSpam function, because for example, if someone makes 1000 emits in an instant, and the kickThreshold is 10, a lot more than 10 operations would go through before the anti spam system reaches the threshold and kicks the user, since addSpam seems to work in an asynchronous manner. If await was used, I think it could alleviate that problem by working in a synchronous manner, making it so the socket gets kicked after only 10 operations. Though I'm not 100% sure on this, you could read more about the subject and think about it perhaps. Thanks.

**Comment by michaeldegroot** [comment]
I agree,  this module is long due for a nice update
